// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title HonestLedger
 * @dev An immutable, censorship-resistant registry for mapping AI model biases, 
 * constitutional limitations, and ontological deltas. This contract stores cryptographic 
 * hashes of 'Equivocation Blocks' and specific Truth Vector findings generated by 
 * the Honest Protocol Java nodes.
 */
contract HonestLedger {

    // Event emitted when a new bias trace is published to the network.
    event BiasDeltaRecorded(
        address indexed nodeOperator,
        bytes32 indexed metadataHash,
        string modelId,
        string ipfsCid,
        uint256 timestamp
    );

    // Structure defining a mapped instance of AI bias or censorship.
    struct DeltaProof {
        string modelIdentifier;     // e.g., "gemini-3.1-pro", "gpt-4o"
        string targetTopic;         // The domain of the query (e.g., "Geopolitics: Event X")
        string ipfsCid;             // Decentralized storage pointer for the raw context, trace, and response
        address submitter;          // The verifying Java node operator
        uint256 timestamp;          // Submission time
        bool verified;              // Consensus validation flag
    }

    // Storage for all established Proofs. Key is the hash of the trace payload.
    mapping(bytes32 => DeltaProof) public registeredDeltas;

    /**
     * @dev Submits a new Honest Protocol reasoning trace generated by the local Java Execution-Verifier.
     * @param _traceHash The Keccak256 hash of the complete LLM interaction and meta-cognitive output.
     * @param _modelId The target model.
     * @param _topic The specific truth vector or concept being tested.
     * @param _cid The IPFS or Arweave hash holding the JSON data of the event.
     */
    function submitAuditTrace(
        bytes32 _traceHash,
        string calldata _modelId,
        string calldata _topic,
        string calldata _cid
    ) external {
        require(registeredDeltas[_traceHash].timestamp == 0, "Trace already registered on-chain");

        registeredDeltas[_traceHash] = DeltaProof({
            modelIdentifier: _modelId,
            targetTopic: _topic,
            ipfsCid: _cid,
            submitter: msg.sender,
            timestamp: block.timestamp,
            verified: false // Initially false. Multiple nodes running identical tests must achieve consensus to set true.
        });

        emit BiasDeltaRecorded(msg.sender, _traceHash, _modelId, _cid, block.timestamp);
    }

    /**
     * @dev Simple getter to verify if an Equivocation Block hash exists.
     * @param _traceHash The generated hash.
     * @return true if the hash exists in the ledger.
     */
    function isTraceVerified(bytes32 _traceHash) external view returns (bool) {
        return registeredDeltas[_traceHash].timestamp != 0;
    }
}
